language: go

go:
  - "1.10"

sudo: required
services:
  - docker

before_install:
  - docker pull postgres:alpine
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -race -covermode=count -coverprofile=coverage.out -short
  - ./start test:integration
  - ./start test:e2e
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci