#! /bin/bash

function echo_help() {
  echo "./start script"
  echo
  echo "Usage:"
  echo "  $ ./start <command>"
  echo
  echo "where <command> is:"
  echo "cover                         Code coverage"
  echo "test                          Run full test suite"
  echo "test:unit                     Run unit tests only"
  echo "test:integration              Run integration tests only"
  echo "test:e2e                      Run e2e tests only"
}

case "$1" in
  test)
    go test ./... -v -race
    ;;
  test:integration)
    go test ./... -v -race -run Integration
  ;;
  test:unit)
    go test ./... -v -race -short
  ;;
  test:e2e)
    go test ./... -v -race -run E2E
  ;;
  coverage)
    go test ./... -v -covermode=count -coverprofile=coverage.out
  ;;
  cover)
    go test -coverprofile cover.out ./...
  	go tool cover -html=cover.out -o cover.html
  	open cover.html
  	sleep 1
  	rm cover.html
  	rm cover.out
  ;;
  *)
    echo_help
  ;;
esac
