version: 2
jobs:
  build:
    working_directory: /go/src/github.com/raytung/g6
    docker:
      - image: circleci/golang:1.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout
      - run: go get -v -t -d ./...
  test:
    working_directory: /go/src/github.com/raytung/g6
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go test -v -cover -race -coverprofile=./coverage.out ./...
      - run: go get github.com/mattn/goveralls
      - run: /home/ubuntu/.go_workspace/bin/goveralls -coverprofile=/home/ubuntu/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test