version: 2
jobs:
  build:
    working_directory: /go/src/github.com/raytung/g6
    docker:
      - image: circleci/golang:1.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build
  unit_test:
    working_directory: /go/src/github.com/raytung/g6
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go test -v -cover -race -coverprofile=./coverage.out ./... -short
      - run: go get -u github.com/mattn/goveralls
      - run: $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
  e2e_test:
      working_directory: /go/src/github.com/raytung/g6
      docker:
        - image: circleci/golang:1.10
      steps:
        - checkout
        - run: ./start test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - e2e_test:
          requires:
            - unit_test